--- #YAML:1.0
name:               Music-Tag
version:            0.4103
abstract:           Interface for collecting information about music files.
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Options:  0.07
    Data::Dumper:     2
    DateTimeX::Easy:  0.088
    Digest::SHA1:     2.11
    Encode:           2.12
    File::Copy:       2
    File::Slurp:      1
    File::Spec:       3.24
    File::stat:       1
    IO::Dir:          1
    IO::File:         1.13
    Locale::Country:  2.07
    Readonly:         1
    Scalar::Util:     1.21
    Test::More:       0.1
    Time::Local:      1.1901
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
