# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-Tag
version:      0.19
version_from: lib/Music/Tag.pm
installdirs:  site
requires:
    Audio::FLAC::Header:           1.4
    Cache::Cache:                  1.05
    HTML::Parser:                  3.56
    LWP:                           0.01
    MP3::Info:                     .9701
    MP3::Tag:                      0.01
    MP4::Info:                     0.01
    Net::Amazon:                   0.01
    Ogg::Vorbis::Header::PurePerl: 0.01
    URI::Escape:                   0.01
    URI::WithBase:                 0.01
    WebService::MusicBrainz:       0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
